//
// Created by tim on 19.12.23.
//

#ifndef MPI_ASSERTION_CHECKING_PRECOMPUTE_INSERTION_H
#define MPI_ASSERTION_CHECKING_PRECOMPUTE_INSERTION_H

#endif // MPI_ASSERTION_CHECKING_PRECOMPUTE_INSERTION_H
