#!/bin/bash

source $1 # the setup_env.sh generated by cmake
source $2 # the script for the tested mini app

if [ ! -d "$APP_NAME" ]; then
  # download if necessary
  download $APP_NAME
fi
GREP_STRING="WARNING: ThreadSanitizer: data race"

rm -f ${APP_NAME}_normal.exe ${APP_NAME}_modified.exe # make sure to detect any build error
build_tsan_normal $APP_NAME ${PWD}/${APP_NAME}_normal.exe
build_tsan_modified $APP_NAME ${PWD}/${APP_NAME}_modified.exe

if [[ ! -x "./${APP_NAME}_normal.exe" ]]; then
  echo "build error"
  exit -1
fi
if [[ ! -x "./${APP_NAME}_modified.exe" ]]; then
  echo "build error"
  exit -1
fi


if ./${APP_NAME}_normal.exe $TEST_INVOCATION_PARAMETER 2>&1 | grep -qF "$GREP_STRING"; then
  echo "Original tsan detected race in original application"
  exit -1
fi

if ./${APP_NAME}_modified.exe $TEST_INVOCATION_PARAMETER 2>&1 | grep -qF "$GREP_STRING"; then
  echo "modified tsan detected race in original application"
  exit -1
fi


rm -f ${APP_NAME}_normal.exe ${APP_NAME}_modified.exe # make sure to detect any build error
patch_datarace $APP_NAME
build_tsan_normal $APP_NAME ${PWD}/${APP_NAME}_normal.exe
build_tsan_modified $APP_NAME ${PWD}/${APP_NAME}_modified.exe
unpatch_datarace $APP_NAME

if [[ ! -x "./${APP_NAME}_normal.exe" ]]; then
  echo "build error"
  exit -1
fi
if [[ ! -x "./${APP_NAME}_modified.exe" ]]; then
  echo "build error"
  exit -1
fi


if ./${APP_NAME}_normal.exe $TEST_INVOCATION_PARAMETER 2>&1 | grep -qF "$GREP_STRING"; then
  echo "Original tsan detected injected race"
  if ./${APP_NAME}_modified.exe $TEST_INVOCATION_PARAMETER 2>&1 | grep -qF "$GREP_STRING"; then
    echo "modified tsan detected injected race"
    # success: both detected the race
    exit 0
  fi
fi

echo  "either implementation did not find injected race"
exit -1