
#include "precalculation_function_analysis.h"
#include "openmp_runtime_functions.h"
#include "precalculation.h"
#include "std_funcs.h"

using namespace llvm;

// this function is Generated by AI
std::string
extract_function_without_namespace(const std::string &qualifiedName) {
  std::istringstream iss(qualifiedName);
  std::vector<std::string> tokens;

  // Tokenize the string by '::'
  std::string token;
  while (std::getline(iss, token, ':')) {
    if (!token.empty()) {
      tokens.push_back(token);
    }
  }

  // Get the last token (function name)
  if (!tokens.empty()) {
    return tokens.back();
  } else {
    // Handle the case where the input string is empty or has no tokens
    return "";
  }
}

// removes all template args from the given name
std::string get_name_without_templates(const std::string &demangled_name) {
  auto pos = demangled_name.begin();
  auto end_pos = pos;
  auto start_pos = pos;

  std::string result = "";
  int template_nesting_level = 0;

  while (pos != demangled_name.end()) {
    if (*pos == '<') {
      if (template_nesting_level == 0) {
        start_pos = pos;
        // directly use std::copy?
        result += std::string(end_pos, pos);
      }
      template_nesting_level++;
    }
    // if template_nesting_level==0 whe are looking at operator> or >>
    if (*pos == '>' && template_nesting_level > 0) {
      template_nesting_level--;
      if (template_nesting_level == 0) {
        end_pos = pos + 1;
      }
    }

    ++pos;
    // special case for operators << or <
    if (pos == demangled_name.end() && template_nesting_level != 0) {
      // ignore the first < and re-start processing from there
      template_nesting_level = 0;
      pos = start_pos + 1;
    }
  }

  assert(template_nesting_level == 0);
  result = result + std::string(end_pos, pos);

  return result;
}

// only gets the name of a function if a demangled name contains a return
// param or template args
std::string get_function_name(const std::string &demangled_name) {
  auto no_template = get_name_without_templates(demangled_name);

  std::istringstream iss(no_template);
  std::string item;
  std::vector<std::string> elems;
  while (std::getline(iss, item, ' ')) {
    elems.push_back(item);
  }

  if (elems.size() > 1) {
    // find the element with the '('
    for (size_t i = 0; i < elems.size(); ++i) {
      if (elems[i].rfind('(') != std::string::npos) {
        if (i != 0 && elems[i - 1].rfind("operator") != std::string::npos) {
          return elems[i - 1] + " " + elems[i];
        } else {
          return elems[i];
        }
      }
    }
  }

  return no_template;
}

PrecalculationFunctionAnalysis::PrecalculationFunctionAnalysis(
    llvm::Function *F, PrecalculationAnalysis *precalc)
    : func(F), precalculatioanalysis(precalc) {
  // assert(not F->isDeclaration() && "Cannot analyze external function");

  is_func_ptr_captured = false;
  aliases.insert(func);

  for (auto *u : func->users()) {
    if (auto *alias = llvm::dyn_cast<llvm::GlobalAlias>(u)) {
      assert(alias->getAliasee() == func);
      aliases.insert(alias);

      if (not alias->user_empty()) {
        llvm::errs() << "Function Alias is used:\n";
        alias->dump();
        llvm::errs() << "Replace with original func\n";
        // this way we dont need to handle tha alias explicitly:
        alias->replaceAllUsesWith(func);
        // this may impact debug info
      }
    }
  }
  // new calls in func.users if aliases arte replaced
  for (auto *u : func->users()) {
    if (auto call = llvm::dyn_cast<llvm::CallBase>(u)) {
      if (call->getCalledFunction() != func) {
        if (is_omp_fork_call(call)) {
          //  call to openmp
          if (!is_openmp_parallel) {
            is_openmp_parallel = true;
            parallel_region = std::make_shared<ParallelRegion>(func);
          }
        } else if (call->getCalledFunction() ==
                   get_omp_functions(*call->getModule())->kmpc_omp_task_alloc) {
          is_openmp_task = true;
          task_alloc_calls.push_back(call);
        } else {
          is_func_ptr_captured = true;
        }
      }
      // else call instruction to function
    } else {
      is_func_ptr_captured = true;
    }
  }
};

void PrecalculationFunctionAnalysis::analyze_can_except_in_precompute(
    const PrecalculationAnalysis *precompute_analysis) {
  // the precompute_analysis object is not fully initialized yet, as we are
  // currently analyzing the functions
  assert(not analysis_except_in_precompute);

  if (func->hasFnAttribute(llvm::Attribute::NoUnwind)) {
    // no exception possible
    can_except_in_precompute = false;
    return;
  }

  if (is_allocation(func)      // out of mem is fatal
      || is_mpi_function(func) // mpi cannot throw recoverable exceptions
  ) {
    can_except_in_precompute = false;
    return;
  }

  if (func->isIntrinsic()) {
    // intrinsics cannot fail
    can_except_in_precompute = false;
    return;
  }

  if (func->isDeclaration()) {
    // don't know: need to assume it can throw
    // func->dump();
    assert(can_except_in_precompute);
    return;
  }

  if (is_func_from_std(func)) {
    // we don't analyze std's internals, assume it can throw
    assert(can_except_in_precompute);
    return;
  }

  analysis_except_in_precompute = true; // this one is currently analyzed
  for (auto &BB : *func) {
    for (auto &inst : BB) {
      if (auto *call = dyn_cast<CallBase>(&inst)) {
        if (not is_interaction_with_cout(call)) {
          for (auto *cc :
               precompute_analysis->get_possible_call_targets(call)) {
            auto callee = precompute_analysis->get_function_analysis(cc);
            assert(callees.find(callee) != callees.end());
            // callee may not be properly initialized yet
            if (not callee->analysis_except_in_precompute) {
              callee->analyze_can_except_in_precompute(precompute_analysis);
            }
            if (callee->can_except_in_precompute &&
                (not(callee == shared_from_this()))) {
              analysis_except_in_precompute = false;
              assert(can_except_in_precompute);
              // TODO better analysis needed??
              //  if they invoke the function that may except they need to
              //  resume exception handling aka if they catch and deal with
              //  exception: they dont throw
              return;
            }
          }
        }
      }
    }
  }

  // no callee can except (this implies that no call to trow was detected)
  analysis_except_in_precompute = false;
  can_except_in_precompute = false;
}

void PrecalculationFunctionAnalysis::re_visit_callsites() {
  // TODO recursively re visit calls that may lead to this callsite??

  assert(precalculatioanalysis);
  for (auto *c : callsites) {
    if (precalculatioanalysis->is_tainted(c)) {
      auto ti = precalculatioanalysis->get_taint_info(c);
      ti->visited = false;
    }
  }
}

void PrecalculationFunctionAnalysis::getPtrRead_recursive_impl(
    std::set<std::shared_ptr<PtrUsageInfo>> &result,
    std::set<std::shared_ptr<const PrecalculationFunctionAnalysis>> &visited)
    const {
  auto pair = visited.insert(shared_from_this());
  if (pair.second) {
    // was inserted
    for (const auto &ptr : ptr_read) {
      result.insert(ptr);
    }
    for (const auto &c : callees) {
      if (auto callee = c.lock()) {
        callee->getPtrRead_recursive_impl(result, visited);
      }
    }
  }
}

std::set<std::shared_ptr<PtrUsageInfo>>
PrecalculationFunctionAnalysis::getPtrRead_recursive() const {
  std::set<std::shared_ptr<PtrUsageInfo>> result;
  std::set<std::shared_ptr<const PrecalculationFunctionAnalysis>> visited;
  getPtrRead_recursive_impl(result, visited);

  return result;
}

void PrecalculationFunctionAnalysis::getPtrWritten_recursive_impl(
    std::set<std::shared_ptr<PtrUsageInfo>> &result,
    std::set<std::shared_ptr<const PrecalculationFunctionAnalysis>> &visited)
    const {
  auto pair = visited.insert(shared_from_this());
  if (pair.second) {
    // was inserted
    for (const auto &ptr : ptr_written) {
      result.insert(ptr);
    }
    for (const auto &c : callees) {
      if (auto callee = c.lock()) {
        callee->getPtrWritten_recursive_impl(result, visited);
      }
    }
  }
}

std::set<std::shared_ptr<PtrUsageInfo>>
PrecalculationFunctionAnalysis::getPtrWritten_recursive() const {
  std::set<std::shared_ptr<PtrUsageInfo>> result;
  std::set<std::shared_ptr<const PrecalculationFunctionAnalysis>> visited;
  getPtrWritten_recursive_impl(result, visited);

  return result;
}
