diff --git a/Makefile b/Makefile
index 96f416e..fe5efd8 100644
--- a/Makefile
+++ b/Makefile
@@ -47,8 +47,11 @@
 #
 # 0) Specify compiler and linker:
 
-CXX=/usr/local/bin/g++
-LINKER=/usr/local/bin/g++
+CXX=$(CLANG_WRAP_CXX)
+LINKER=$(CLANG_WRAP_CXX)
+#CXX=clang++
+#LINKER=clang++
+
 #CXX=mpicxx
 #LINKER=mpicxx
 
@@ -77,7 +80,7 @@ USE_MPI =
 
 #IA32 with GCC: 
 #CPP_OPT_FLAGS = -O3 -funroll-all-loops -malign-double
-CPP_OPT_FLAGS = -O3 -ftree-vectorize -ftree-vectorizer-verbose=2
+CPP_OPT_FLAGS = -g -O3 -ftree-vectorize $(SANITIZE_FLAG) -flto -fwhole-program-vtables -fuse-ld=lld
 
 #
 # 4) MPI library:
@@ -94,14 +97,14 @@ CPP_OPT_FLAGS = -O3 -ftree-vectorize -ftree-vectorizer-verbose=2
 #    If you want to run the program with OpenMP, make sure USING_OMP is set
 #    to -DUSING_OMP
 
-USE_OMP = 
-#USE_OMP = -DUSING_OMP
+#USE_OMP = 
+USE_OMP = -DUSING_OMP
 
 #
 # 6) OpenMP Compiler argument
 #    GCC and Intel compilers require -fopenmp and -openmp, resp.  Other compilers may differ.
 
-#OMP_FLAGS = -fopenmp
+OMP_FLAGS = -fopenmp
 #OMP_FLAGS = -openmp
 
 #
